name: "CI"

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]

defaults:
  run:
    shell: "bash"

env:
  CI_RELEASE: "${{ github.event_name == 'release' }}"
  STACK_VERSION: "2.7.3"

jobs:
  build:
    strategy:
      fail-fast: false # do not cancel builds for other OSes if one fails
      matrix:
        include:
          - # If upgrading the Haskell image, also upgrade it in the lint job below
            os: "ubuntu-latest"
            image: "haskell:8.10.7-stretch@sha256:100f8fb7d7d8d64adb5e106fe8136b8d4cbdc03aeb2cbd145a7597d74b69bafb"
          - os: "macOS-10.15"
          - os: "windows-2019"

    runs-on: "${{ matrix.os }}"
    container: "${{ matrix.image }}"

    steps:
      - uses: "actions/setup-node@v2"
        with:
          node-version: "14"

      - run: |
          npm -v
          npm i -g spago@0.20.8
          spago --version
